from airflow import DAG
from airflow.providers.google.cloud.operators.bigquery import BigQueryInsertJobOperator, BigQueryCreateEmptyDatasetOperator
from airflow.providers.google.cloud.operators.gcs import GCSListObjectsOperator, GCSCreateBucketOperator
from airflow.providers.common.sql.operators.sql import SQLExecuteQueryOperator
from airflow.operators.python import PythonOperator

from datetime import datetime
from airflow.sdk import get_current_context

from w2_ingest_taxi_gcp import *

with DAG(
    dag_id="ny_taxi_gcp_test_dag",
    start_date=datetime(2024, 1, 1),
    schedule= '0 9 1 * *',
    catchup=False,
) as dag:
    
    create_bucket_task = GCSCreateBucketOperator(
        task_id="create_gcs_bucket",
        bucket_name=BUCKET_NAME,
        location="us-central1",
        gcp_conn_id="gcp-conn-id-1",
        storage_class="STANDARD",
    )

    extract_yellow_task = PythonOperator(
        task_id="extract_yellow_to_gcs",
        python_callable=extract_yellow,
        dag=dag
        )
    
    extract_green_task = PythonOperator(
        task_id="extract_green_to_gcs",
        python_callable=extract_green,
        dag=dag
        )

    bq_create_yellow_tripdata = BigQueryInsertJobOperator(
        task_id="bq_create_yellow_tripdata",
        gcp_conn_id='gcp-conn-id-1',
        configuration={
            "query": {
                "query": f"""
                    CREATE TABLE IF NOT EXISTS `{PROJECT_ID}.{DATASET_ID}.yellow_taxi_tripdata` (
                        unique_row_id BYTES OPTIONS (description = 'A unique identifier for the trip, generated by hashing key trip attributes.'),
                        filename STRING OPTIONS (description = 'The source filename from which the trip data was loaded.'),
                        VendorID STRING OPTIONS (description = 'Provider code'),
                        tpep_pickup_datetime TIMESTAMP,
                        tpep_dropoff_datetime TIMESTAMP,
                        passenger_count INTEGER,
                        trip_distance NUMERIC,
                        RatecodeID STRING,
                        store_and_fwd_flag STRING,
                        PULocationID STRING,
                        DOLocationID STRING,
                        payment_type INTEGER,
                        fare_amount NUMERIC,
                        extra NUMERIC,
                        mta_tax NUMERIC,
                        tip_amount NUMERIC,
                        tolls_amount NUMERIC,
                        improvement_surcharge NUMERIC,
                        total_amount NUMERIC,
                        congestion_surcharge NUMERIC
                    )
                    PARTITION BY DATE(tpep_pickup_datetime)
                """,
                "useLegacySql": False,
            }
        }
    )

    bq_create_yellow_staging= BigQueryInsertJobOperator(
        task_id="bq_create_yellow_staging",
        gcp_conn_id='gcp-conn-id-1',
        configuration={
            "query": {
                "query": f"""
                CREATE OR REPLACE EXTERNAL TABLE `{PROJECT_ID}.{DATASET_ID}.yellow_taxi_ext`
                (
                    VendorID STRING,
                    tpep_pickup_datetime TIMESTAMP,
                    tpep_dropoff_datetime TIMESTAMP,
                    passenger_count INTEGER,
                    trip_distance NUMERIC,
                    RatecodeID STRING,
                    store_and_fwd_flag STRING,
                    PULocationID STRING,
                    DOLocationID STRING,
                    payment_type INTEGER,
                    fare_amount NUMERIC,
                    extra NUMERIC,
                    mta_tax NUMERIC,
                    tip_amount NUMERIC,
                    tolls_amount NUMERIC,
                    improvement_surcharge NUMERIC,
                    total_amount NUMERIC,
                    congestion_surcharge NUMERIC
                )
                OPTIONS (
                    format = 'CSV',
                    uris = ['gs://{BUCKET_NAME}/yellow/{{{{ ti.xcom_pull(task_ids="extract_yellow_to_gcs") }}}}'],
                    skip_leading_rows = 1,
                    ignore_unknown_values = TRUE
                )
                """,
                "useLegacySql": False,
            }
        }
    )

    bq_add_yellow_unique_id = BigQueryInsertJobOperator(
        task_id="bq_add_yellow_unique_id",
        gcp_conn_id='gcp-conn-id-1',
        configuration={
            "query": {
                "query": f"""
                    CREATE OR REPLACE TABLE `{PROJECT_ID}.{DATASET_ID}.yellow_taxi_tripdata_tmp` AS
                    SELECT
                        MD5(CONCAT(
                            COALESCE(CAST(VendorID AS STRING), ""),
                            COALESCE(CAST(tpep_pickup_datetime AS STRING), ""),
                            COALESCE(CAST(tpep_dropoff_datetime AS STRING), ""),
                            COALESCE(CAST(PULocationID AS STRING), ""),
                            COALESCE(CAST(DOLocationID AS STRING), "")
                        )) AS unique_row_id,
                        '{{ ti.xcom_pull(task_ids="extract_yellow_to_gcs") }}' AS filename,
                        *
                    FROM `{PROJECT_ID}.{DATASET_ID}.yellow_taxi_ext`
                """
            }
        }
    )

    bq_merge_yellow = BigQueryInsertJobOperator(
        task_id="bq_merge_yellow",
        gcp_conn_id='gcp-conn-id-1',
        configuration={
            "query": {
                "query": f"""
                    MERGE INTO {PROJECT_ID}.{DATASET_ID}.yellow_taxi_tripdata T
                    USING {PROJECT_ID}.{DATASET_ID}.yellow_taxi_tripdata_tmp S
                    ON T.unique_row_id = S.unique_row_id
                    WHEN NOT MATCHED THEN
                    INSERT (unique_row_id, filename, VendorID, tpep_pickup_datetime, tpep_dropoff_datetime, passenger_count, trip_distance,
                        RatecodeID, store_and_fwd_flag, PULocationID, DOLocationID, payment_type, fare_amount, extra, mta_tax,
                        tip_amount, tolls_amount, improvement_surcharge, total_amount, congestion_surcharge 
                    )
                    VALUES (S.unique_row_id, S.filename, S.VendorID, S.tpep_pickup_datetime, S.tpep_dropoff_datetime, S.passenger_count, S.trip_distance,
                        S.RatecodeID, S.store_and_fwd_flag, S.PULocationID, S.DOLocationID, S.payment_type, S.fare_amount, S.extra, S.mta_tax,
                        S.tip_amount, S.tolls_amount, S.improvement_surcharge, S.total_amount, S.congestion_surcharge
                    )
                """
            }
        }
    )

    bq_create_green_tripdata = BigQueryInsertJobOperator(
        task_id="bq_create_green_tripdata",
        gcp_conn_id='gcp-conn-id-1',
        configuration={
            "query": {
                "query": f"""
                    CREATE TABLE IF NOT EXISTS `{PROJECT_ID}.{DATASET_ID}.green_taxi_tripdata` (
                        unique_row_id BYTES OPTIONS (description = 'A unique identifier for the trip, generated by hashing key trip attributes.'),
                        filename STRING OPTIONS (description = 'The source filename from which the trip data was loaded.'),
                        VendorID STRING OPTIONS (description = 'Provider code'),
                        tpep_pickup_datetime TIMESTAMP,
                        tpep_dropoff_datetime TIMESTAMP,
                        passenger_count INTEGER,
                        trip_distance NUMERIC,
                        RatecodeID STRING,
                        store_and_fwd_flag STRING,
                        PULocationID STRING,
                        DOLocationID STRING,
                        payment_type INTEGER,
                        trip_type INTEGER,
                        ehail_fee NUMERIC,
                        fare_amount NUMERIC,
                        extra NUMERIC,
                        mta_tax NUMERIC,
                        tip_amount NUMERIC,
                        tolls_amount NUMERIC,
                        improvement_surcharge NUMERIC,
                        total_amount NUMERIC,
                        congestion_surcharge NUMERIC
                    )
                    PARTITION BY DATE(tpep_pickup_datetime)
                """,
                "useLegacySql": False,
            }
        }
    )

    bq_create_green_staging= BigQueryInsertJobOperator(
        task_id="bq_create_green_staging",
        gcp_conn_id='gcp-conn-id-1',
        configuration={
            "query": {
                "query": f"""
                CREATE OR REPLACE EXTERNAL TABLE `{PROJECT_ID}.{DATASET_ID}.green_taxi_ext`
                (
                    VendorID STRING,
                    tpep_pickup_datetime TIMESTAMP,
                    tpep_dropoff_datetime TIMESTAMP,
                    passenger_count INTEGER,
                    trip_distance NUMERIC,
                    RatecodeID STRING,
                    store_and_fwd_flag STRING,
                    PULocationID STRING,
                    DOLocationID STRING,
                    payment_type INTEGER,
                    trip_type INTEGER,
                    ehail_fee NUMERIC,
                    fare_amount NUMERIC,
                    extra NUMERIC,
                    mta_tax NUMERIC,
                    tip_amount NUMERIC,
                    tolls_amount NUMERIC,
                    improvement_surcharge NUMERIC,
                    total_amount NUMERIC,
                    congestion_surcharge NUMERIC
                )
                OPTIONS (
                    format = 'CSV',
                    uris = ['gs://{BUCKET_NAME}/green/{{{{ ti.xcom_pull(task_ids="extract_green_to_gcs") }}}}'],
                    skip_leading_rows = 1,
                    ignore_unknown_values = TRUE
                )
                """,
                "useLegacySql": False,
            }
        }
    )

    bq_add_green_unique_id = BigQueryInsertJobOperator(
        task_id="bq_add_green_unique_id",
        gcp_conn_id='gcp-conn-id-1',
        configuration={
            "query": {
                "query": f"""
                    CREATE OR REPLACE TABLE `{PROJECT_ID}.{DATASET_ID}.green_taxi_tripdata_tmp` AS
                    SELECT
                        MD5(CONCAT(
                            COALESCE(CAST(VendorID AS STRING), ""),
                            COALESCE(CAST(tpep_pickup_datetime AS STRING), ""),
                            COALESCE(CAST(tpep_dropoff_datetime AS STRING), ""),
                            COALESCE(CAST(PULocationID AS STRING), ""),
                            COALESCE(CAST(DOLocationID AS STRING), "")
                        )) AS unique_row_id,
                        '{{{{ ti.xcom_pull(task_ids="extract_green_to_gcs") }}}}' AS filename,
                        *
                    FROM `{PROJECT_ID}.{DATASET_ID}.green_taxi_ext`
                """
            }
        }
    )

    bq_merge_green = BigQueryInsertJobOperator(
        task_id="bq_merge_green",
        gcp_conn_id='gcp-conn-id-1',
        configuration={
            "query": {
                "query": f"""
                    MERGE INTO {PROJECT_ID}.{DATASET_ID}.green_taxi_tripdata T
                    USING {PROJECT_ID}.{DATASET_ID}.green_taxi_tripdata_tmp S
                    ON T.unique_row_id = S.unique_row_id
                    WHEN NOT MATCHED THEN
                    INSERT (unique_row_id, filename, VendorID, tpep_pickup_datetime, tpep_dropoff_datetime, passenger_count, trip_distance,
                        RatecodeID, store_and_fwd_flag, PULocationID, DOLocationID, payment_type, fare_amount, extra, mta_tax,
                        tip_amount, tolls_amount, improvement_surcharge, total_amount, congestion_surcharge, ehail_fee, trip_type
                    )
                    VALUES (S.unique_row_id, S.filename, S.VendorID, S.tpep_pickup_datetime, S.tpep_dropoff_datetime, S.passenger_count, S.trip_distance,
                        S.RatecodeID, S.store_and_fwd_flag, S.PULocationID, S.DOLocationID, S.payment_type, S.fare_amount, S.extra, S.mta_tax,
                        S.tip_amount, S.tolls_amount, S.improvement_surcharge, S.total_amount, S.congestion_surcharge, S.ehail_fee, S.trip_type
                    )
                """
            }
        }
    )

    create_bucket_task >> [extract_yellow_task, extract_green_task]
    extract_yellow_task >> [bq_create_yellow_tripdata, bq_create_yellow_staging >> bq_add_yellow_unique_id ] 
    bq_add_yellow_unique_id >> bq_merge_yellow
    extract_green_task >> [bq_create_green_tripdata, bq_create_green_staging >> bq_add_green_unique_id ] 
    bq_add_green_unique_id >> bq_merge_green