from airflow import DAG
from airflow.providers.google.cloud.operators.bigquery import BigQueryInsertJobOperator, BigQueryCreateEmptyDatasetOperator
from airflow.providers.google.cloud.operators.gcs import GCSListObjectsOperator, GCSCreateBucketOperator
from airflow.providers.common.sql.operators.sql import SQLExecuteQueryOperator
from airflow.operators.python import PythonOperator

from datetime import datetime
from airflow.sdk import get_current_context

from ingest_taxi_gcp import *

with DAG(
    dag_id="ny_taxi_gcp_test_dag",
    start_date=datetime(2024, 1, 1),
    schedule=None,
    catchup=False,
) as dag:
    
    create_bucket_task = GCSCreateBucketOperator(
        task_id="create_gcs_bucket",
        bucket_name=BUCKET_NAME,
        location="us-central1",
        gcp_conn_id="gcp-conn-id-1",
        storage_class="STANDARD",
    )

    extract_yellow_task = PythonOperator(
        task_id="extract_yellow_to_gcs",
        python_callable=extract_yellow,
        dag=dag
        )
    
    # extract_green_task = PythonOperator(
    #     task_id="extract_green_to_gcs",
    #     python_callable=extract_green,
    #     dag=dag
    #     )

    bq_create_yellow_tripdata = BigQueryInsertJobOperator(
        task_id="bq_create_yellow_tripdata",
        gcp_conn_id='gcp-conn-id-1',
        configuration={
            "query": {
                "query": f"""
                    CREATE TABLE IF NOT EXISTS `{PROJECT_ID}.{DATASET_ID}.yellow_taxi_tripdata` (
                        unique_row_id BYTES OPTIONS (description = 'A unique identifier for the trip, generated by hashing key trip attributes.'),
                        filename STRING OPTIONS (description = 'The source filename from which the trip data was loaded.'),
                        VendorID STRING OPTIONS (description = 'Provider code'),
                        tpep_pickup_datetime TIMESTAMP,
                        tpep_dropoff_datetime TIMESTAMP,
                        passenger_count INTEGER,
                        trip_distance NUMERIC,
                        RatecodeID STRING,
                        store_and_fwd_flag STRING,
                        PULocationID STRING,
                        DOLocationID STRING,
                        payment_type INTEGER,
                        fare_amount NUMERIC,
                        extra NUMERIC,
                        mta_tax NUMERIC,
                        tip_amount NUMERIC,
                        tolls_amount NUMERIC,
                        improvement_surcharge NUMERIC,
                        total_amount NUMERIC,
                        congestion_surcharge NUMERIC
                    )
                    PARTITION BY DATE(tpep_pickup_datetime)
                """,
                "useLegacySql": False,
            }
        }
    )

    bq_create_yellow_staging= BigQueryInsertJobOperator(
        task_id="bq_create_yellow_staging",
        gcp_conn_id='gcp-conn-id-1',
        configuration={
            "query": {
                "query": f"""
                CREATE OR REPLACE EXTERNAL TABLE `{PROJECT_ID}.{DATASET_ID}.yellow_taxi_ext`
                (
                    VendorID STRING,
                    tpep_pickup_datetime TIMESTAMP,
                    tpep_dropoff_datetime TIMESTAMP,
                    passenger_count INTEGER,
                    trip_distance NUMERIC,
                    RatecodeID STRING,
                    store_and_fwd_flag STRING,
                    PULocationID STRING,
                    DOLocationID STRING,
                    payment_type INTEGER,
                    fare_amount NUMERIC,
                    extra NUMERIC,
                    mta_tax NUMERIC,
                    tip_amount NUMERIC,
                    tolls_amount NUMERIC,
                    improvement_surcharge NUMERIC,
                    total_amount NUMERIC,
                    congestion_surcharge NUMERIC
                )
                OPTIONS (
                    format = 'CSV',
                    uris = ['gs://{BUCKET_NAME}/{{{{ ti.xcom_pull(task_ids="extract_yellow_to_gcs") }}}}'],
                    skip_leading_rows = 1,
                    ignore_unknown_values = TRUE
                )
                """,
                "useLegacySql": False,
            }
        }
    )

    create_bucket_task >> extract_yellow_task >> [bq_create_yellow_staging, bq_create_yellow_tripdata]